// <auto-generated />
namespace MovieOnline.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class dropcontraint : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dropcontraint));
        
        string IMigrationMetadata.Id
        {
            get { return "202002141507273_drop-contraint"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
